disabled_rules:
- cyclomatic_complexity
- multiple_closures_with_trailing_closure
- vertical_parameter_alignment
included:
- GoodGame

line_length:
 - 160 #warning
 - 200 #error

file_length:
 - 1000 #warning
 - 1500 #error

function_body_length:
 - 100 #warning
 - 150 #error

type_body_length:
 - 450 #warning
 - 1000 #error

identifier_name:
 excluded: # excluded via string array
 - id

min_length:
warning: 3
